# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.DateTimeField(verbose_name='report_month')),
                ('area', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=300)),
                ('visitor_num', models.IntegerField(default=0)),
            ],
        ),
    ]
