# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='report_month',
            field=models.CharField(max_length=100),
        ),
    ]
