# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20160723_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('area_cht', models.CharField(max_length=200)),
                ('area_eng', models.CharField(max_length=200)),
                ('purpose_cht', models.CharField(max_length=300)),
                ('purpose_eng', models.CharField(max_length=300)),
                ('visitor_num', models.IntegerField(default=0)),
            ],
        ),
    ]
