# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_auto_20160928_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalrecord',
            name='report_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arrivalrecord',
            name='report_year',
            field=models.IntegerField(default=0),
        ),
    ]
